version: 2.1

jobs:
  build:
    machine:
      image: default
    resource_class: medium
    steps:
      - checkout
      - run:
          name: Install Dagger CLI
          command: cd /usr/local && { curl -L https://dl.dagger.io/dagger/install.sh | sudo sh; cd -; }
      - run:
          name: test ts init 
          command: dagger init --sdk=typescript potato
      - run:
          name: test ts functions first run 
          command: dagger -m potato functions
      - run:
          name: test ts functions second run 
          command: dagger -m potato functions
      - run:
          name: test go init 
          command: dagger init --sdk=go gotato
      - run:
          name: test go functions first run 
          command: dagger -m gotato functions
      - run:
          name: test go functions second run 
          command: dagger -m gotato functions
      - run:
          name: test python init 
          command: dagger init --sdk=go pytato
      - run:
          name: test python functions first run 
          command: dagger -m pytato functions
      - run:
          name: test python functions second run 
          command: dagger -m pytato functions
      - run:
          name: Stop Dagger Engine
          command: docker stop -t 300 $(docker ps --filter name="dagger-engine-*" -q)
  windows:
    resource_class: "windows.medium"
    machine:
      image: "windows-server-2022-gui:current"
      shell: "powershell.exe -ExecutionPolicy Bypass"
    steps:
      - checkout 
      - run:
          name: Install Dagger CLI 
          command: Invoke-WebRequest -UseBasicParsing -Uri https://dl.dagger.io/dagger/install.ps1 | Invoke-Expression
      - run:
          name: Execute Dagger CLI 
          command: C:\Users\circleci\dagger\dagger.exe version

  notify_all:
    docker:
      - image: cimg/go:1.17
    resource_class: medium 
    steps:
      - checkout 
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Install Dagger CLI
          command: cd /usr/local && { curl -L https://dl.dagger.io/dagger/install.sh | sudo sh; cd -; }
      - run:
          name: testing interpolation
          command: |
            echo ${CIRCLE_TAG//\//@}
      - run:
          name: testing interpolation
          command: |
            dagger -m "github.com/levlaz/${CIRCLE_TAG//\//@}" functions

workflows:
  qa:
    jobs:
      - build
      - windows
  notify:
    jobs:
      - notify_all:
          filters:
            tags:
              only: /.*v.*/
            branches:
              ignore: /.*/