version: 2.1

jobs:
  build:
    machine:
      image: default
    resource_class: medium
    steps:
      - checkout
      - run:
          name: Install Dagger CLI
          command: cd /usr/local && { curl -L https://dl.dagger.io/dagger/install.sh | sudo sh; cd -; }
      - run:
          name: test ts init 
          command: dagger init --sdk=typescript potato
      - run:
          name: test ts functions first run 
          command: dagger -m potato functions
      - run:
          name: test ts functions second run 
          command: dagger -m potato functions
      - run:
          name: Stop Dagger Engine
          command: docker stop -t 300 $(docker ps --filter name="dagger-engine-*" -q)